name: My Workflow
on:
  release:
    types: [published]
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: ${{ github.ref_name }}

    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        tags: lyc95/random_num:${{ github.ref_name }}

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "SA54 Submission",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: Li Youcheng \n Matriculation: A0249467M \n Email: youcheng.li@u.nus.edu \n Repo: ${{ github.repositoryUrl }} \n Image name: lyc95/random_numbers:${{ github.ref_name }} \n Image url: https://hub.docker.com/repository/docker/lyc95/random_num"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK